#!/usr/local/bin/perl
use strict;
use warnings;

use XML::Atom::Stream;

my $url = shift || "http://danga.com:8081/atom-stream.xml";

my $client = XML::Atom::Stream->new(callback => \&callback);
$client->connect($url);

sub callback {
    my $feed = shift;
    my $entry = ($feed->entries)[0];
    print $entry->title . " (by " . $feed->author->name . ")\n",
        "  ", $entry->link->href, "\n";
}
